import { NextResponse } from 'next/server'
import { getSession } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { evaluateContent, BENCHMARKS } from '@/lib/scoring'
import { checkSafety } from '@/lib/safety'

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const user = await getSession()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { id } = await params
  const stage = await prisma.stage.findUnique({
    where: { id },
    include: { project: true },
  })

  if (!stage) return NextResponse.json({ error: 'Stage not found' }, { status: 404 })

  // Update stage status
  await prisma.stage.update({
    where: { id },
    data: { status: 'submitted', submittedAt: new Date() },
  })

  // Update project status
  await prisma.project.update({
    where: { id: stage.projectId },
    data: { status: 'submitted' },
  })

  // Get chat messages for this stage to build a content description
  const messages = await prisma.chatMessage.findMany({
    where: { projectId: stage.projectId, stageType: stage.stageType },
    orderBy: { createdAt: 'asc' },
  })

  const contentDescription = [
    stage.chatbotSummary || '',
    ...messages.map((m) => m.content),
  ].join(' ')

  // Run auto-evaluation
  const result = evaluateContent(contentDescription, stage.project.ageBracket, stage.stageType)

  const evaluation = await prisma.evaluation.create({
    data: {
      stageId: id,
      evaluationType: 'auto',
      overallScore: result.overallScore,
      overallGrade: result.overallGrade,
      summary: `Auto-evaluation for ${stage.stageType} stage. Overall score: ${result.overallScore}/10.`,
      suggestedSteps: JSON.stringify([
        'Review domain scores and address areas below threshold',
        'Discuss results with the Maka chatbot for specific improvement suggestions',
        'Consider strengthening lower-scoring domains before advancing',
      ]),
      version: stage.version,
      domainScores: {
        create: result.domainScores.map((d) => ({
          domain: d.domain,
          score: d.score,
          grade: d.grade,
          feedback: d.feedback,
          benchmark: d.benchmark,
          subIndicators: {
            create: d.subIndicators.map((si) => ({
              indicatorName: si.indicatorName,
              score: si.score,
              maxScore: si.maxScore,
            })),
          },
        })),
      },
    },
  })

  // Run safety checks
  const safetyFlags = checkSafety(contentDescription, stage.project.ageBracket)
  if (safetyFlags.length > 0) {
    for (const flag of safetyFlags) {
      await prisma.safetyFlag.create({
        data: {
          stageId: id,
          flagType: flag.flagType,
          severity: flag.severity,
          description: flag.description,
          autoGenerated: true,
        },
      })
    }
  }

  // Create notification
  await prisma.notification.create({
    data: {
      userId: user.id,
      type: 'eval_complete',
      title: 'Evaluation Complete',
      message: `Your ${stage.stageType} for "${stage.project.title}" has been evaluated. Score: ${result.overallGrade}`,
      link: `/projects/${stage.projectId}`,
    },
  })

  return NextResponse.json({ evaluation, result })
}
